package com.example.film_rental_app.payment_reportsmodule.dto.response;

import java.math.BigDecimal;
import java.time.LocalDateTime;

// Defines what the client receives after any payment operation
// Contains both IDs and human-readable names for frontend display
// Also carries a "message" field so the frontend can show backend-driven success messages
public class PaymentResponseDTO {

    // Success message set by the controller (e.g. "Payment created!", "Payment deleted!")
    // Not mapped from the entity — manually set in controller before returning response
    private String message;

    // Generated by DB on save — not present in request
    private Integer paymentId;

    private BigDecimal amount;
    private LocalDateTime paymentDate;

    private Integer customerId;
    // Mapper joins firstName + lastName from entity into one field
    private String customerName;

    private Integer staffId;
    // Mapper joins firstName + lastName from entity into one field
    private String staffName;

    // Optional — not every payment is linked to a rental
    private Integer rentalId;

    // Auto-set by DB on every save — not sent by client
    private LocalDateTime lastUpdate;

    // No-args constructor required by Jackson for serialization/deserialization
    public PaymentResponseDTO() {}

    // ── Getters ───────────────────────────────────────────────────────────────
    // Called by Spring (Jackson) at runtime to build the JSON response

    // Returns the success/info message set by the controller
    public String getMessage() { return message; }

    // Returns the DB-generated payment ID
    public Integer getPaymentId() { return paymentId; }

    // Returns the payment amount (e.g. 3.99, 4.99)
    public BigDecimal getAmount() { return amount; }

    // Returns the timestamp of when the payment was made
    public LocalDateTime getPaymentDate() { return paymentDate; }

    // Returns the ID of the customer who made the payment
    public Integer getCustomerId() { return customerId; }

    // Returns the full name of the customer (firstName + lastName joined by mapper)
    public String getCustomerName() { return customerName; }

    // Returns the ID of the staff member who processed the payment
    public Integer getStaffId() { return staffId; }

    // Returns the full name of the staff member (firstName + lastName joined by mapper)
    public String getStaffName() { return staffName; }

    // Returns the rental ID linked to this payment (null if no rental)
    public Integer getRentalId() { return rentalId; }

    // Returns the last DB update timestamp (auto-managed, not editable by client)
    public LocalDateTime getLastUpdate() { return lastUpdate; }

    // ── Setters ───────────────────────────────────────────────────────────────
    // Called by PaymentMapper to fill each field, and by controller to set the message

    // Set by controller after create/delete to send a human-readable result to frontend
    public void setMessage(String message) { this.message = message; }

    // Set by mapper from the saved/fetched Payment entity
    public void setPaymentId(Integer paymentId) { this.paymentId = paymentId; }

    // Set by mapper from the payment entity's amount field
    public void setAmount(BigDecimal amount) { this.amount = amount; }

    // Set by mapper from the payment entity's paymentDate field
    public void setPaymentDate(LocalDateTime paymentDate) { this.paymentDate = paymentDate; }

    // Set by mapper from the linked Customer entity's ID
    public void setCustomerId(Integer customerId) { this.customerId = customerId; }

    // Set by mapper by joining customer's firstName + lastName
    public void setCustomerName(String customerName) { this.customerName = customerName; }

    // Set by mapper from the linked Staff entity's ID
    public void setStaffId(Integer staffId) { this.staffId = staffId; }

    // Set by mapper by joining staff's firstName + lastName
    public void setStaffName(String staffName) { this.staffName = staffName; }

    // Set by mapper from the linked Rental entity's ID (may be null)
    public void setRentalId(Integer rentalId) { this.rentalId = rentalId; }

    // Set by mapper from the payment entity's lastUpdate timestamp
    public void setLastUpdate(LocalDateTime lastUpdate) { this.lastUpdate = lastUpdate; }
}