package com.example.film_rental_app.payment_reportsmodule.dto.response;

import java.math.BigDecimal;
import java.time.LocalDateTime;

// Defines what the client receives after any payment operation
// Contains both IDs and human-readable names for frontend display
public class PaymentResponseDTO {

    // Generated by DB on save — not present in request
    private Integer paymentId;

    private BigDecimal amount;
    private LocalDateTime paymentDate;

    private Integer customerId;
    // Mapper joins firstName + lastName from entity into one field
    private String customerName;

    private Integer staffId;
    // Mapper joins firstName + lastName from entity into one field
    private String staffName;

    // Optional — not every payment is linked to a rental
    private Integer rentalId;

    // Auto-set by DB on every save — not sent by client
    private LocalDateTime lastUpdate;

    public PaymentResponseDTO() {}

    // Getters — called by Spring (Jackson) at runtime to build the JSON response
    public Integer getPaymentId() { return paymentId; }
    public BigDecimal getAmount() { return amount; }
    public LocalDateTime getPaymentDate() { return paymentDate; }
    public Integer getCustomerId() { return customerId; }
    public String getCustomerName() { return customerName; }
    public Integer getStaffId() { return staffId; }
    public String getStaffName() { return staffName; }
    public Integer getRentalId() { return rentalId; }
    public LocalDateTime getLastUpdate() { return lastUpdate; }

    // Setters — called by PaymentMapper to fill each field before sending response
    public void setPaymentId(Integer paymentId) { this.paymentId = paymentId; }
    public void setAmount(BigDecimal amount) { this.amount = amount; }
    public void setPaymentDate(LocalDateTime paymentDate) { this.paymentDate = paymentDate; }
    public void setCustomerId(Integer customerId) { this.customerId = customerId; }
    public void setCustomerName(String customerName) { this.customerName = customerName; }
    public void setStaffId(Integer staffId) { this.staffId = staffId; }
    public void setStaffName(String staffName) { this.staffName = staffName; }
    public void setRentalId(Integer rentalId) { this.rentalId = rentalId; }
    public void setLastUpdate(LocalDateTime lastUpdate) { this.lastUpdate = lastUpdate; }
}