package com.example.film_rental_app.payment_reportsmodule.entity;

import com.example.film_rental_app.customer_inventory_rentalmodule.entity.Customer;
import com.example.film_rental_app.customer_inventory_rentalmodule.entity.Rental;
import com.example.film_rental_app.location_store_staffmodule.entity.Staff;
import jakarta.persistence.*;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotNull;
import org.hibernate.annotations.UpdateTimestamp;

import java.math.BigDecimal;
import java.time.LocalDateTime;

// Represents the payment table in the database
@Entity
@Table(name = "payment")
public class Payment {

    // Auto-generated by DB on every new payment — never set manually
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "payment_id")
    private Integer paymentId;

    // Must be at least 0.00 — validated at both DB and application level
    @NotNull
    @DecimalMin("0.00")
    @Column(name = "amount", nullable = false, precision = 5, scale = 2)
    private BigDecimal amount;

    @NotNull
    @Column(name = "payment_date", nullable = false)
    private LocalDateTime paymentDate;

    // Auto-updated by Hibernate every time this record is saved
    @UpdateTimestamp
    @Column(name = "last_update")
    private LocalDateTime lastUpdate;

    // Many payments can belong to one customer
    // LAZY — customer data is only fetched from DB when accessed
    // optional = false means every payment must have a customer
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "customer_id", nullable = false,
            foreignKey = @ForeignKey(name = "fk_payment_customer"))
    private Customer customer;

    // Many payments can belong to one staff member
    // LAZY — staff data is only fetched from DB when accessed
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "staff_id", nullable = false,
            foreignKey = @ForeignKey(name = "fk_payment_staff"))
    private Staff staff;

    // Rental is optional — a payment may not always be linked to a rental
    // LAZY — rental data is only fetched from DB when accessed
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rental_id",
            foreignKey = @ForeignKey(name = "fk_payment_rental"))
    private Rental rental;

    // Required by JPA — do not remove
    public Payment() {}

    // Used when all fields are known upfront
    public Payment(Integer paymentId, BigDecimal amount, LocalDateTime paymentDate,
                   LocalDateTime lastUpdate, Customer customer, Staff staff, Rental rental) {
        this.paymentId   = paymentId;
        this.amount      = amount;
        this.paymentDate = paymentDate;
        this.lastUpdate  = lastUpdate;
        this.customer    = customer;
        this.staff       = staff;
        this.rental      = rental;
    }

    // Getters and Setters — used by JPA and mapper to read and write fields
    public Integer getPaymentId()               { return paymentId; }
    public void setPaymentId(Integer paymentId) { this.paymentId = paymentId; }

    public BigDecimal getAmount()               { return amount; }
    public void setAmount(BigDecimal amount)    { this.amount = amount; }

    public LocalDateTime getPaymentDate()                    { return paymentDate; }
    public void setPaymentDate(LocalDateTime paymentDate)    { this.paymentDate = paymentDate; }

    public LocalDateTime getLastUpdate()                     { return lastUpdate; }
    public void setLastUpdate(LocalDateTime lastUpdate)      { this.lastUpdate = lastUpdate; }

    public Customer getCustomer()               { return customer; }
    public void setCustomer(Customer customer)  { this.customer = customer; }

    public Staff getStaff()                     { return staff; }
    public void setStaff(Staff staff)           { this.staff = staff; }

    public Rental getRental()                   { return rental; }
    public void setRental(Rental rental)        { this.rental = rental; }

    // Relationships excluded to avoid infinite recursion during logging
    @Override
    public String toString() {
        return "Payment{" +
                "paymentId=" + paymentId +
                ", amount=" + amount +
                ", paymentDate=" + paymentDate +
                ", lastUpdate=" + lastUpdate +
                '}';
    }
}